version: '3.8'
name: forge-server
services:
  server:
    container_name: jdk-vm
    image: eclipse-temurin:17-jdk-focal
    #command : ["tail", "-f", "/dev/null"]
    #command: [java, -version]
    working_dir: /server
    command: ./run.sh nogui
    # restart: on-failure
    expose:
        - 25565
        - 25575
    ports:
        - "25565:25565"
        - "25575:25575"
    volumes:
      - ./server:/server

    